// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using libraryManagement.Models;

#nullable disable

namespace libraryManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("libraryManagement.Models.Library", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryName")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("PublishedYear")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("BookId");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorName = "Balaguruswamy",
                            BookName = "C++",
                            CategoryName = 1,
                            IsDeleted = false,
                            Price = 500,
                            PublishedYear = 2001,
                            UpdatedOn = new DateTime(2019, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 2,
                            AuthorName = "Mazidi",
                            BookName = "Microcontrollers",
                            CategoryName = 2,
                            IsDeleted = false,
                            Price = 550,
                            PublishedYear = 2002,
                            UpdatedOn = new DateTime(2019, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 3,
                            AuthorName = "Sebastian",
                            BookName = "Robotics",
                            CategoryName = 3,
                            IsDeleted = false,
                            Price = 600,
                            PublishedYear = 2003,
                            UpdatedOn = new DateTime(2019, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 4,
                            AuthorName = "Jacques Heyman",
                            BookName = "Structural Engineering",
                            CategoryName = 4,
                            IsDeleted = false,
                            Price = 800,
                            PublishedYear = 2004,
                            UpdatedOn = new DateTime(2019, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 5,
                            AuthorName = "Michael Faraday",
                            BookName = "DC Motors",
                            CategoryName = 5,
                            IsDeleted = false,
                            Price = 400,
                            PublishedYear = 2004,
                            UpdatedOn = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 6,
                            AuthorName = "Nassim Nicholas",
                            BookName = "Economics",
                            CategoryName = 6,
                            IsDeleted = true,
                            Price = 300,
                            PublishedYear = 2005,
                            UpdatedOn = new DateTime(2019, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 7,
                            AuthorName = "-",
                            BookName = "Data Structure",
                            CategoryName = 1,
                            IsDeleted = false,
                            Price = 430,
                            PublishedYear = 2006,
                            UpdatedOn = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 8,
                            AuthorName = "Abraham Silberschatz",
                            BookName = "Operating Systems",
                            CategoryName = 1,
                            IsDeleted = true,
                            Price = 560,
                            PublishedYear = 2007,
                            UpdatedOn = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BookId = 9,
                            AuthorName = "Wikliam Gothmann",
                            BookName = "Digital Electronics",
                            CategoryName = 2,
                            IsDeleted = false,
                            Price = 730,
                            PublishedYear = 2005,
                            UpdatedOn = new DateTime(2019, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
