CREATE TABLE UserTable
(
ID INT NOT NULL PRIMARY KEY,
FirstName VARCHAR(255),
LastName VARCHAR(255),
Email VARCHAR(255),
City VARCHAR(255),
Salary INT,
Designation VARCHAR(255),
CreatedDate DATETIME,
ModifiedDate DATETIME,
IsActive BIT
)

CREATE TABLE GroupTable
(
ID INT NOT NULL PRIMARY KEY,
Name VARCHAR(255),
Description VARCHAR(1024),
CreatedDate DATETIME,
ModifiedDate DATETIME,
IsActive BIT
)

CREATE TABLE UserGroup 
(
ID INT NOT NULL PRIMARY KEY,
GroupID INT, FOREIGN KEY(GroupID) REFERENCES GroupTable(ID),
UserID INT, FOREIGN KEY(UserID) REFERENCES UserTable(ID),
ModifiedDate DATETIME,
IsActive BIT
)